"""
Pediatrics score router endpoints
"""

from fastapi import APIRouter

from .aap_pediatric_hypertension import router as aap_pediatric_hypertension_router
from .apgar_score import router as apgar_score_router
from .asthma_predictive_index import router as asthma_predictive_index_router
from .bacterial_meningitis_score import router as bacterial_meningitis_score_router
from .behavioral_observational_pain_scale import router as behavioral_observational_pain_scale_router
from .bishop_score import router as bishop_score_router
from .brue import router as brue_router
from .brue_2_0 import router as brue_2_0_router
from .catch_rule import router as catch_rule_router
from .chalice_rule import router as chalice_rule_router
from .cheops_pain_scale import router as cheops_pain_scale_router
from .capd import router as capd_router
from .dhaka_score import router as dhaka_score_router
from .eat_sleep_console import router as eat_sleep_console_router
from .neonatal_early_onset_sepsis import router as neonatal_early_onset_sepsis_router
from .neonatal_partial_exchange_polycythemia import router as neonatal_partial_exchange_polycythemia_router
from .hour_specific_neonatal_hyperbilirubinemia import router as hour_specific_neonatal_hyperbilirubinemia_router
from .infant_scalp_score import router as infant_scalp_score_router
from .immunization_schedule_calculator import router as immunization_schedule_calculator_router
from .intrauterine_rbc_transfusion_dosage import router as intrauterine_rbc_transfusion_dosage_router
from .kawasaki_disease_diagnostic_criteria import router as kawasaki_disease_diagnostic_criteria_router
from .lansky_play_performance_scale import router as lansky_play_performance_scale_router
from .maintenance_fluids_calculations import router as maintenance_fluids_calculations_router
from .modified_asthma_predictive_index import router as modified_asthma_predictive_index_router
from .modified_finnegan_neonatal_abstinence_score import router as modified_finnegan_neonatal_abstinence_score_router
from .oxygenation_index import router as oxygenation_index_router
from .phoenix_sepsis_score import router as phoenix_sepsis_score_router
from .wat_1_pediatric_withdrawal import router as wat_1_pediatric_withdrawal_router

# Create main specialty router
router = APIRouter()

router.include_router(aap_pediatric_hypertension_router)
router.include_router(apgar_score_router)
router.include_router(asthma_predictive_index_router)
router.include_router(bacterial_meningitis_score_router)
router.include_router(behavioral_observational_pain_scale_router)
router.include_router(bishop_score_router)
router.include_router(brue_router)
router.include_router(brue_2_0_router)
router.include_router(catch_rule_router)
router.include_router(chalice_rule_router)
router.include_router(cheops_pain_scale_router)
router.include_router(capd_router)
router.include_router(dhaka_score_router)
router.include_router(eat_sleep_console_router)
router.include_router(neonatal_early_onset_sepsis_router)
router.include_router(neonatal_partial_exchange_polycythemia_router)
router.include_router(hour_specific_neonatal_hyperbilirubinemia_router)
router.include_router(infant_scalp_score_router)
router.include_router(immunization_schedule_calculator_router)
router.include_router(intrauterine_rbc_transfusion_dosage_router)
router.include_router(kawasaki_disease_diagnostic_criteria_router)
router.include_router(lansky_play_performance_scale_router)
router.include_router(maintenance_fluids_calculations_router)
router.include_router(modified_asthma_predictive_index_router)
router.include_router(modified_finnegan_neonatal_abstinence_score_router)
router.include_router(oxygenation_index_router)
router.include_router(phoenix_sepsis_score_router)
router.include_router(wat_1_pediatric_withdrawal_router)
