"""
Neurology score router endpoints
"""

from fastapi import APIRouter

from .abcd2 import router as abcd2_router
from .four_at import router as four_at_router
from .abc2_ich_volume import router as abc2_ich_volume_router
from .aspects import router as aspects_router
from .ascod_algorithm import router as ascod_algorithm_router
from .astral_score import router as astral_score_router
from .awol_score import router as awol_score_router
from .barnes_jewish_dysphagia import router as barnes_jewish_dysphagia_router
from .canadian_tia_score import router as canadian_tia_score_router
from .cerebral_perfusion_pressure import router as cerebral_perfusion_pressure_router
from .clinical_dementia_rating import router as clinical_dementia_rating_router
from .ndi import router as ndi_router
from .disease_steps_ms import router as disease_steps_ms_router
from .dragon_score import router as dragon_score_router
from .embolic_stroke_undetermined_source_esus_criteria import router as embolic_stroke_undetermined_source_esus_criteria_router
from .neuropathic_pain_scale import router as neuropathic_pain_scale_router
from .new_orleans_charity_head_trauma import router as new_orleans_charity_head_trauma_router
from .edss import router as edss_router
from .fisher_grading_scale import router as fisher_grading_scale_router
from .four_score import router as four_score_router
from .gcs_pupils_score import router as gcs_pupils_score_router
from .glasgow_coma_scale import router as glasgow_coma_scale_router
from .func_score import router as func_score_router
from .hat_score import router as hat_score_router
from .hints import router as hints_router
from .hunt_hess_classification import router as hunt_hess_classification_router
from .impact_score import router as impact_score_router
from .iwg2_alzheimer_criteria import router as iwg2_alzheimer_criteria_router
from .ich_score import router as ich_score_router
from .los_angeles_motor_scale import router as los_angeles_motor_scale_router
from .mcdonald_criteria_multiple_sclerosis_2017_revision import router as mcdonald_criteria_multiple_sclerosis_2017_revision_router
from .midas import router as midas_router
from .mtoq_4 import router as mtoq_4_router
from .modified_fatigue_impact_scale import router as modified_fatigue_impact_scale_router
from .modified_fisher_grading_scale import router as modified_fisher_grading_scale_router
from .modified_hoehn_and_yahr_scale import router as modified_hoehn_and_yahr_scale_router
from .modified_nih_stroke_scale import router as modified_nih_stroke_scale_router
from .modified_rankin_scale import router as modified_rankin_scale_router
from .modified_rankin_score_9q import router as modified_rankin_score_9q_router
from .modified_soar_score import router as modified_soar_score_router
from .moca import router as moca_router
from .mg_adl import router as mg_adl_router
from .nihss import router as nihss_router
from .onls import router as onls_router
from .sudbury_vertigo_risk_score import router as sudbury_vertigo_risk_score_router
from .tpa_contraindications import router as tpa_contraindications_router
from .trunk_impairment_scale import router as trunk_impairment_scale_router

# Create main specialty router
router = APIRouter()

router.include_router(abcd2_router)
router.include_router(four_at_router)
router.include_router(abc2_ich_volume_router)
router.include_router(aspects_router)
router.include_router(ascod_algorithm_router)
router.include_router(astral_score_router)
router.include_router(awol_score_router)
router.include_router(barnes_jewish_dysphagia_router)
router.include_router(canadian_tia_score_router)
router.include_router(cerebral_perfusion_pressure_router)
router.include_router(clinical_dementia_rating_router)
router.include_router(ndi_router)
router.include_router(disease_steps_ms_router)
router.include_router(dragon_score_router)
router.include_router(embolic_stroke_undetermined_source_esus_criteria_router)
router.include_router(neuropathic_pain_scale_router)
router.include_router(new_orleans_charity_head_trauma_router)
router.include_router(edss_router)
router.include_router(fisher_grading_scale_router)
router.include_router(four_score_router)
router.include_router(gcs_pupils_score_router)
router.include_router(glasgow_coma_scale_router)
router.include_router(func_score_router)
router.include_router(hat_score_router)
router.include_router(hints_router)
router.include_router(hunt_hess_classification_router)
router.include_router(impact_score_router)
router.include_router(iwg2_alzheimer_criteria_router)
router.include_router(ich_score_router)
router.include_router(los_angeles_motor_scale_router)
router.include_router(mcdonald_criteria_multiple_sclerosis_2017_revision_router)
router.include_router(midas_router)
router.include_router(mtoq_4_router)
router.include_router(modified_fatigue_impact_scale_router)
router.include_router(modified_fisher_grading_scale_router)
router.include_router(modified_hoehn_and_yahr_scale_router)
router.include_router(modified_nih_stroke_scale_router)
router.include_router(modified_rankin_scale_router)
router.include_router(modified_rankin_score_9q_router)
router.include_router(modified_soar_score_router)
router.include_router(moca_router)
router.include_router(mg_adl_router)
router.include_router(nihss_router)
router.include_router(onls_router)
router.include_router(sudbury_vertigo_risk_score_router)
router.include_router(tpa_contraindications_router)
router.include_router(trunk_impairment_scale_router)
