"""
Emergency score router endpoints
"""

from fastapi import APIRouter

from .four_c_mortality import router as four_c_mortality_router
from .ais_inhalation_injury import router as ais_inhalation_injury_router
from .injury_severity_score import router as injury_severity_score_router
from .emergency_medicine_coding_guide_2023 import router as emergency_medicine_coding_guide_2023_router
from .abc_score import router as abc_score_router
from .acep_ed_covid19_management_tool import router as acep_ed_covid19_management_tool_router
from .acetaminophen_overdose_nac import router as acetaminophen_overdose_nac_router
from .adapt_protocol import router as adapt_protocol_router
from .age_adjusted_d_dimer import router as age_adjusted_d_dimer_router
from .aims65 import router as aims65_router
from .alt_70_cellulitis import router as alt_70_cellulitis_router
from .altitude_adjusted_perc import router as altitude_adjusted_perc_router
from .alvarado_score import router as alvarado_score_router
from .antivenom_dosing_algorithm import router as antivenom_dosing_algorithm_router
from .apache_ii_score import router as apache_ii_score_router
from .air_score import router as air_score_router
from .abg_analyzer import router as abg_analyzer_router
from .basic_statistics_calc import router as basic_statistics_calc_router
from .bastion_classification import router as bastion_classification_router
from .behavioral_pain_scale import router as behavioral_pain_scale_router
from .benzodiazepine_conversion import router as benzodiazepine_conversion_router
from .bicarbonate_deficit import router as bicarbonate_deficit_router
from .bisap_score import router as bisap_score_router
from .blast_lung_injury_severity import router as blast_lung_injury_severity_router
from .burch_wartofsky_point_scale import router as burch_wartofsky_point_scale_router
from .canadian_c_spine_rule import router as canadian_c_spine_rule_router
from .canadian_ct_head_rule import router as canadian_ct_head_rule_router
from .canadian_syncope_risk_score import router as canadian_syncope_risk_score_router
from .caprini_score_2005 import router as caprini_score_2005_router
from .cart_score import router as cart_score_router
from .centor_score import router as centor_score_router
from .cedocs_score import router as cedocs_score_router
from .chip_prediction_rule import router as chip_prediction_rule_router
from .chosen_covid_discharge import router as chosen_covid_discharge_router
from .covid_inpatient_risk_calculator import router as covid_inpatient_risk_calculator_router
from .cincinnati_prehospital_stroke_severity_scale import router as cincinnati_prehospital_stroke_severity_scale_router
from .cam_icu import router as cam_icu_router
from .covid_gram_critical_illness import router as covid_gram_critical_illness_router
from .cpot_pain_observation import router as cpot_pain_observation_router
from .danger_assessment_tool import router as danger_assessment_tool_router
from .ed_safe_patient_safety_screener import router as ed_safe_patient_safety_screener_router
from .naloxone_drip_dosing import router as naloxone_drip_dosing_router
from .news import router as news_router
from .news_2 import router as news_2_router
from .nedocs import router as nedocs_router
from .digifab_dosing import router as digifab_dosing_router
from .emergency_department_assessment_chest_pain_edacs import router as emergency_department_assessment_chest_pain_edacs_router
from .emergency_heart_failure_mortality_risk_grade_ehmrg import router as emergency_heart_failure_mortality_risk_grade_ehmrg_router
from .nexus_criteria import router as nexus_criteria_router
from .newsom_score import router as newsom_score_router
from .nexus_chest_ct import router as nexus_chest_ct_router
from .nexus_chest_blunt_trauma import router as nexus_chest_blunt_trauma_router
from .ottawa_ankle_rule import router as ottawa_ankle_rule_router
from .ottawa_copd_risk_scale import router as ottawa_copd_risk_scale_router
from .ottawa_heart_failure_risk_scale import router as ottawa_heart_failure_risk_scale_router
from .ottawa_knee_rule import router as ottawa_knee_rule_router
from .ottawa_sah_rule import router as ottawa_sah_rule_router
from .psi_port_score import router as psi_port_score_router
from .pesi import router as pesi_router
from .pe_sard_score import router as pe_sard_score_router
from .qsofa_score import router as qsofa_score_router
from .qcsi import router as qcsi_router
from .embed import router as embed_router
from .ett_depth_tidal_volume import router as ett_depth_tidal_volume_router
from .fast import router as fast_router
from .fomepizole_dosing import router as fomepizole_dosing_router
from .go_far_score import router as go_far_score_router
from .gupta_mica import router as gupta_mica_router
from .gupta_postoperative_pneumonia_risk import router as gupta_postoperative_pneumonia_risk_router
from .gupta_postoperative_respiratory_failure_risk import router as gupta_postoperative_respiratory_failure_risk_router
from .hacor_score import router as hacor_score_router
from .hacks_impairment_index import router as hacks_impairment_index_router
from .he_macs import router as he_macs_router
from .hestia_criteria import router as hestia_criteria_router
from .hark import router as hark_router
from .hits_score import router as hits_score_router
from .hope_score import router as hope_score_router
from .intraoperative_fluid_dosing import router as intraoperative_fluid_dosing_router
from .iv_drip_rate_calculator import router as iv_drip_rate_calculator_router
from .kings_college_criteria_acetaminophen import router as kings_college_criteria_acetaminophen_router
from .kocher_criteria_septic_arthritis import router as kocher_criteria_septic_arthritis_router
from .lace_index_readmission import router as lace_index_readmission_router
from .local_anesthetic_dosing_calculator import router as local_anesthetic_dosing_calculator_router
from .lrinec_score import router as lrinec_score_router
from .lung_injury_prediction_score import router as lung_injury_prediction_score_router
from .macocha_score import router as macocha_score_router
from .mangled_extremity_severity_score import router as mangled_extremity_severity_score_router
from .mrc_icu_score import router as mrc_icu_score_router
from .modified_early_warning_score import router as modified_early_warning_score_router
from .modified_brain_injury_guideline import router as modified_brain_injury_guideline_router
from .modified_mallampati_classification import router as modified_mallampati_classification_router
from .modified_sofa import router as modified_sofa_router
from .rose_rule import router as rose_rule_router
from .roth_score import router as roth_score_router
from .rox_index import router as rox_index_router
from .rule_of_7s_lyme_meningitis import router as rule_of_7s_lyme_meningitis_router
from .rule_of_nines import router as rule_of_nines_router
from .tpa_alteplase_dosing_stroke import router as tpa_alteplase_dosing_stroke_router
from .triss import router as triss_router
from .winters_formula_metabolic_acidosis import router as winters_formula_metabolic_acidosis_router
from .wisconsin_criteria_maxillofacial_trauma import router as wisconsin_criteria_maxillofacial_trauma_router
from .woman_abuse_screening_tool import router as woman_abuse_screening_tool_router
from .years_algorithm_pe import router as years_algorithm_pe_router
from .utah_covid19_risk_score import router as utah_covid19_risk_score_router
from .rems_score import router as rems_score_router

# Create main specialty router
router = APIRouter()

router.include_router(four_c_mortality_router)
router.include_router(ais_inhalation_injury_router)
router.include_router(injury_severity_score_router)
router.include_router(emergency_medicine_coding_guide_2023_router)
router.include_router(abc_score_router)
router.include_router(acep_ed_covid19_management_tool_router)
router.include_router(acetaminophen_overdose_nac_router)
router.include_router(adapt_protocol_router)
router.include_router(age_adjusted_d_dimer_router)
router.include_router(aims65_router)
router.include_router(alt_70_cellulitis_router)
router.include_router(altitude_adjusted_perc_router)
router.include_router(alvarado_score_router)
router.include_router(antivenom_dosing_algorithm_router)
router.include_router(apache_ii_score_router)
router.include_router(air_score_router)
router.include_router(abg_analyzer_router)
router.include_router(basic_statistics_calc_router)
router.include_router(bastion_classification_router)
router.include_router(behavioral_pain_scale_router)
router.include_router(benzodiazepine_conversion_router)
router.include_router(bicarbonate_deficit_router)
router.include_router(bisap_score_router)
router.include_router(blast_lung_injury_severity_router)
router.include_router(burch_wartofsky_point_scale_router)
router.include_router(canadian_c_spine_rule_router)
router.include_router(canadian_ct_head_rule_router)
router.include_router(canadian_syncope_risk_score_router)
router.include_router(caprini_score_2005_router)
router.include_router(cart_score_router)
router.include_router(centor_score_router)
router.include_router(cedocs_score_router)
router.include_router(chip_prediction_rule_router)
router.include_router(chosen_covid_discharge_router)
router.include_router(covid_inpatient_risk_calculator_router)
router.include_router(cincinnati_prehospital_stroke_severity_scale_router)
router.include_router(cam_icu_router)
router.include_router(covid_gram_critical_illness_router)
router.include_router(cpot_pain_observation_router)
router.include_router(danger_assessment_tool_router)
router.include_router(ed_safe_patient_safety_screener_router)
router.include_router(naloxone_drip_dosing_router)
router.include_router(news_router)
router.include_router(news_2_router)
router.include_router(nedocs_router)
router.include_router(digifab_dosing_router)
router.include_router(emergency_department_assessment_chest_pain_edacs_router)
router.include_router(emergency_heart_failure_mortality_risk_grade_ehmrg_router)
router.include_router(nexus_criteria_router)
router.include_router(newsom_score_router)
router.include_router(nexus_chest_ct_router)
router.include_router(nexus_chest_blunt_trauma_router)
router.include_router(ottawa_ankle_rule_router)
router.include_router(ottawa_copd_risk_scale_router)
router.include_router(ottawa_heart_failure_risk_scale_router)
router.include_router(ottawa_knee_rule_router)
router.include_router(ottawa_sah_rule_router)
router.include_router(psi_port_score_router)
router.include_router(pesi_router)
router.include_router(pe_sard_score_router)
router.include_router(qsofa_score_router)
router.include_router(qcsi_router)
router.include_router(embed_router)
router.include_router(ett_depth_tidal_volume_router)
router.include_router(fast_router)
router.include_router(fomepizole_dosing_router)
router.include_router(go_far_score_router)
router.include_router(gupta_mica_router)
router.include_router(gupta_postoperative_pneumonia_risk_router)
router.include_router(gupta_postoperative_respiratory_failure_risk_router)
router.include_router(hacor_score_router)
router.include_router(hacks_impairment_index_router)
router.include_router(he_macs_router)
router.include_router(hestia_criteria_router)
router.include_router(hark_router)
router.include_router(hits_score_router)
router.include_router(hope_score_router)
router.include_router(intraoperative_fluid_dosing_router)
router.include_router(iv_drip_rate_calculator_router)
router.include_router(kings_college_criteria_acetaminophen_router)
router.include_router(kocher_criteria_septic_arthritis_router)
router.include_router(lace_index_readmission_router)
router.include_router(local_anesthetic_dosing_calculator_router)
router.include_router(lrinec_score_router)
router.include_router(lung_injury_prediction_score_router)
router.include_router(macocha_score_router)
router.include_router(mangled_extremity_severity_score_router)
router.include_router(mrc_icu_score_router)
router.include_router(modified_early_warning_score_router)
router.include_router(modified_brain_injury_guideline_router)
router.include_router(modified_mallampati_classification_router)
router.include_router(modified_sofa_router)
router.include_router(rose_rule_router)
router.include_router(roth_score_router)
router.include_router(rox_index_router)
router.include_router(rule_of_7s_lyme_meningitis_router)
router.include_router(rule_of_nines_router)
router.include_router(tpa_alteplase_dosing_stroke_router)
router.include_router(triss_router)
router.include_router(winters_formula_metabolic_acidosis_router)
router.include_router(wisconsin_criteria_maxillofacial_trauma_router)
router.include_router(woman_abuse_screening_tool_router)
router.include_router(years_algorithm_pe_router)
router.include_router(utah_covid19_risk_score_router)
router.include_router(rems_score_router)
