"""
Emergency score router endpoints
"""

from fastapi import APIRouter

from .four_c_mortality import router as four_c_mortality_router
from .ais_inhalation_injury import router as ais_inhalation_injury_router
from .emergency_medicine_coding_guide_2023 import router as emergency_medicine_coding_guide_2023_router
from .abc_score import router as abc_score_router
from .acep_ed_covid19_management_tool import router as acep_ed_covid19_management_tool_router
from .acetaminophen_overdose_nac import router as acetaminophen_overdose_nac_router
from .adapt_protocol import router as adapt_protocol_router
from .age_adjusted_d_dimer import router as age_adjusted_d_dimer_router
from .aims65 import router as aims65_router
from .alt_70_cellulitis import router as alt_70_cellulitis_router
from .altitude_adjusted_perc import router as altitude_adjusted_perc_router
from .alvarado_score import router as alvarado_score_router
from .antivenom_dosing_algorithm import router as antivenom_dosing_algorithm_router
from .apache_ii_score import router as apache_ii_score_router
from .air_score import router as air_score_router
from .abg_analyzer import router as abg_analyzer_router
from .basic_statistics_calc import router as basic_statistics_calc_router
from .bastion_classification import router as bastion_classification_router
from .behavioral_pain_scale import router as behavioral_pain_scale_router
from .benzodiazepine_conversion import router as benzodiazepine_conversion_router
from .bicarbonate_deficit import router as bicarbonate_deficit_router
from .bisap_score import router as bisap_score_router
from .blast_lung_injury_severity import router as blast_lung_injury_severity_router

# Create main specialty router
router = APIRouter()

router.include_router(four_c_mortality_router)
router.include_router(ais_inhalation_injury_router)
router.include_router(emergency_medicine_coding_guide_2023_router)
router.include_router(abc_score_router)
router.include_router(acep_ed_covid19_management_tool_router)
router.include_router(acetaminophen_overdose_nac_router)
router.include_router(adapt_protocol_router)
router.include_router(age_adjusted_d_dimer_router)
router.include_router(aims65_router)
router.include_router(alt_70_cellulitis_router)
router.include_router(altitude_adjusted_perc_router)
router.include_router(alvarado_score_router)
router.include_router(antivenom_dosing_algorithm_router)
router.include_router(apache_ii_score_router)
router.include_router(air_score_router)
router.include_router(abg_analyzer_router)
router.include_router(basic_statistics_calc_router)
router.include_router(bastion_classification_router)
router.include_router(behavioral_pain_scale_router)
router.include_router(benzodiazepine_conversion_router)
router.include_router(bicarbonate_deficit_router)
router.include_router(bisap_score_router)
router.include_router(blast_lung_injury_severity_router)
