"""
Oncology Routers

Router endpoints for oncology/cancer-related medical scores.
"""

from fastapi import APIRouter
from .leibovich_2018_rcc import router as leibovich_2018_rcc_router
from .asymptomatic_myeloma_prognosis import router as asymptomatic_myeloma_prognosis_router
from .bclc_staging import router as bclc_staging_router
from .bmv_model import router as bmv_model_router
from .carg_tt import router as carg_tt_router
from .crash_score import router as crash_score_router
from .cisne import router as cisne_router
from .ctcae import router as ctcae_router
from .crs_grading import router as crs_grading_router
from .damico_risk_classification import router as damico_risk_classification_router
from .delta_p_score import router as delta_p_score_router
from .ecog_performance_status import router as ecog_performance_status_router
from .fong_clinical_risk_score import router as fong_clinical_risk_score_router
from .gail_model_breast_cancer_risk import router as gail_model_breast_cancer_risk_router
from .galad_model_hcc import router as galad_model_hcc_router
from .gi_gpa import router as gi_gpa_router
from .imdc_risk_model import router as imdc_risk_model_router
from .immune_related_adverse_events_endocrine_diabetes import router as immune_related_adverse_events_endocrine_diabetes_router
from .immune_related_adverse_events_endocrine_hypothyroidism import router as immune_related_adverse_events_endocrine_hypothyroidism_router
from .immune_related_adverse_events_gi_colitis import router as immune_related_adverse_events_gi_colitis_router
from .immune_related_adverse_events_gi_hepatitis import router as immune_related_adverse_events_gi_hepatitis_router
from .immune_related_adverse_events_lung_pneumonitis import router as immune_related_adverse_events_lung_pneumonitis_router
from .immune_related_adverse_events_renal_nephritis import router as immune_related_adverse_events_renal_nephritis_router
from .karnofsky_performance_status import router as karnofsky_performance_status_router
from .khorana_risk_score import router as khorana_risk_score_router
from .lent_prognostic_score import router as lent_prognostic_score_router
from .mekhail_extension_motzer_score import router as mekhail_extension_motzer_score_router
from .mskcc_motzer_score import router as mskcc_motzer_score_router
from .metroticket_hcc import router as metroticket_hcc_router
from .mirels_criteria import router as mirels_criteria_router
from .modified_glasgow_prognostic_score import router as modified_glasgow_prognostic_score_router
from .modified_recist import router as modified_recist_router
from .prognostic_index_cancer_outcomes import router as prognostic_index_cancer_outcomes_router
from .promise_score_malignant_pleural_effusion import router as promise_score_malignant_pleural_effusion_router
from .prostate_tumor_volume_density import router as prostate_tumor_volume_density_router
from .psa_doubling_time_calculator import router as psa_doubling_time_calculator_router

router = APIRouter()

# Include all oncology score routers
router.include_router(leibovich_2018_rcc_router)
router.include_router(asymptomatic_myeloma_prognosis_router)
router.include_router(bclc_staging_router)
router.include_router(bmv_model_router)
router.include_router(carg_tt_router)
router.include_router(crash_score_router)
router.include_router(cisne_router)
router.include_router(ctcae_router)
router.include_router(crs_grading_router)
router.include_router(damico_risk_classification_router)
router.include_router(delta_p_score_router)
router.include_router(ecog_performance_status_router)
router.include_router(fong_clinical_risk_score_router)
router.include_router(gail_model_breast_cancer_risk_router)
router.include_router(galad_model_hcc_router)
router.include_router(gi_gpa_router)
router.include_router(imdc_risk_model_router)
router.include_router(immune_related_adverse_events_endocrine_diabetes_router)
router.include_router(immune_related_adverse_events_endocrine_hypothyroidism_router)
router.include_router(immune_related_adverse_events_gi_colitis_router)
router.include_router(immune_related_adverse_events_gi_hepatitis_router)
router.include_router(immune_related_adverse_events_lung_pneumonitis_router)
router.include_router(immune_related_adverse_events_renal_nephritis_router)
router.include_router(karnofsky_performance_status_router)
router.include_router(khorana_risk_score_router)
router.include_router(lent_prognostic_score_router)
router.include_router(mekhail_extension_motzer_score_router)
router.include_router(mskcc_motzer_score_router)
router.include_router(metroticket_hcc_router)
router.include_router(mirels_criteria_router)
router.include_router(modified_glasgow_prognostic_score_router)
router.include_router(modified_recist_router)
router.include_router(prognostic_index_cancer_outcomes_router)
router.include_router(promise_score_malignant_pleural_effusion_router)
router.include_router(prostate_tumor_volume_density_router)
router.include_router(psa_doubling_time_calculator_router)

__all__ = ["router"]
