"""
Cardiology score router endpoints
"""

from fastapi import APIRouter

from .cha2ds2_vasc import router as cha2ds2_vasc_router
from .subtle_anterior_stemi_4_variable import router as subtle_anterior_stemi_4_variable_router
from .gwtg_heart_failure_risk_score import router as gwtg_heart_failure_risk_score_router
from .h2fpef_score import router as h2fpef_score_router
from .acc_aha_hf_staging import router as acc_aha_hf_staging_router
from .acef_ii import router as acef_ii_router
from .action_icu_nstemi import router as action_icu_nstemi_router
from .adhere_algorithm import router as adhere_algorithm_router
from .thakar_score import router as thakar_score_router
from .aub_has2_cardiovascular_risk_index import router as aub_has2_cardiovascular_risk_index_router
from .aortic_dissection_detection_risk_score import router as aortic_dissection_detection_risk_score_router
from .ascvd_2013 import router as ascvd_2013_router
from .atria_bleeding import router as atria_bleeding_router
from .atria_stroke import router as atria_stroke_router
from .brugada_criteria_vt import router as brugada_criteria_vt_router
from .cahp_score import router as cahp_score_router
from .ccs_angina_grade import router as ccs_angina_grade_router
from .care_score import router as care_score_router
from .cardiac_output_fick import router as cardiac_output_fick_router
from .cardiac_power_output import router as cardiac_power_output_router
from .chads_65 import router as chads_65_router
from .chads2_score import router as chads2_score_router
from .cha2ds2_va_score import router as cha2ds2_va_score_router
from .corrected_qt_interval import router as corrected_qt_interval_router
from .crusade_bleeding_risk import router as crusade_bleeding_risk_router
from .dapt_score import router as dapt_score_router
from .doac_score import router as doac_score_router
from .duke_activity_status_index import router as duke_activity_status_index_router
from .duke_treadmill_score import router as duke_treadmill_score_router
from .egsys_score_syncope import router as egsys_score_syncope_router
from .euromacs_rhf_score import router as euromacs_rhf_score_router
from .euroscore_ii import router as euroscore_ii_router
from .nyha_functional_classification import router as nyha_functional_classification_router
from .framingham_heart_failure_criteria import router as framingham_heart_failure_criteria_router
from .framingham_risk_score import router as framingham_risk_score_router
from .garfield_af import router as garfield_af_router
from .gillmore_staging_attr_cm import router as gillmore_staging_attr_cm_router
from .grace_acs_risk import router as grace_acs_risk_router
from .grogan_staging_attr_cm import router as grogan_staging_attr_cm_router
from .hcm_risk_scd import router as hcm_risk_scd_router
from .heart_pathway import router as heart_pathway_router
from .heart_score import router as heart_score_router
from .ie_mortality_risk_score import router as ie_mortality_risk_score_router
from .interchest_rule import router as interchest_rule_router
from .jones_criteria_acute_rheumatic_fever import router as jones_criteria_acute_rheumatic_fever_router
from .killip_classification import router as killip_classification_router
from .ldl_calculated import router as ldl_calculated_router
from .maggic_risk_calculator import router as maggic_risk_calculator_router
from .marburg_heart_score import router as marburg_heart_score_router
from .mean_arterial_pressure import router as mean_arterial_pressure_router
from .mehran_score import router as mehran_score_router
from .modified_sgarbossa_criteria import router as modified_sgarbossa_criteria_router
from .score2 import router as score2_router
from .score2_diabetes import router as score2_diabetes_router
from .score2_op import router as score2_op_router
from .troponin_only_macs import router as troponin_only_macs_router
from .us_medped_fh_criteria import router as us_medped_fh_criteria_router
from .virsta_score import router as virsta_score_router

# Create main specialty router
router = APIRouter()

router.include_router(cha2ds2_vasc_router)
router.include_router(subtle_anterior_stemi_4_variable_router)
router.include_router(gwtg_heart_failure_risk_score_router)
router.include_router(h2fpef_score_router)
router.include_router(acc_aha_hf_staging_router)
router.include_router(acef_ii_router)
router.include_router(action_icu_nstemi_router)
router.include_router(adhere_algorithm_router)
router.include_router(thakar_score_router)
router.include_router(aub_has2_cardiovascular_risk_index_router)
router.include_router(aortic_dissection_detection_risk_score_router)
router.include_router(ascvd_2013_router)
router.include_router(atria_bleeding_router)
router.include_router(atria_stroke_router)
router.include_router(brugada_criteria_vt_router)
router.include_router(cahp_score_router)
router.include_router(ccs_angina_grade_router)
router.include_router(care_score_router)
router.include_router(cardiac_output_fick_router)
router.include_router(cardiac_power_output_router)
router.include_router(chads_65_router)
router.include_router(chads2_score_router)
router.include_router(cha2ds2_va_score_router)
router.include_router(corrected_qt_interval_router)
router.include_router(crusade_bleeding_risk_router)
router.include_router(dapt_score_router)
router.include_router(doac_score_router)
router.include_router(duke_activity_status_index_router)
router.include_router(duke_treadmill_score_router)
router.include_router(egsys_score_syncope_router)
router.include_router(euromacs_rhf_score_router)
router.include_router(euroscore_ii_router)
router.include_router(nyha_functional_classification_router)
router.include_router(framingham_heart_failure_criteria_router)
router.include_router(framingham_risk_score_router)
router.include_router(garfield_af_router)
router.include_router(gillmore_staging_attr_cm_router)
router.include_router(grace_acs_risk_router)
router.include_router(grogan_staging_attr_cm_router)
router.include_router(hcm_risk_scd_router)
router.include_router(heart_pathway_router)
router.include_router(heart_score_router)
router.include_router(ie_mortality_risk_score_router)
router.include_router(interchest_rule_router)
router.include_router(jones_criteria_acute_rheumatic_fever_router)
router.include_router(killip_classification_router)
router.include_router(ldl_calculated_router)
router.include_router(maggic_risk_calculator_router)
router.include_router(marburg_heart_score_router)
router.include_router(mean_arterial_pressure_router)
router.include_router(mehran_score_router)
router.include_router(modified_sgarbossa_criteria_router)
router.include_router(score2_router)
router.include_router(score2_diabetes_router)
router.include_router(score2_op_router)
router.include_router(troponin_only_macs_router)
router.include_router(us_medped_fh_criteria_router)
router.include_router(virsta_score_router)
